services:
  - type: web
    name: petshappy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: WKHTMLTOPDF_PATH
        value: /usr/bin/wkhtmltopdf
